---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: clickhouse
  roles:
    - vector
- name: Install lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.apt:
        name: git
        state: present
  roles:
    - lighthouse