---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
        enabled: true
      become: true
  tasks:
    - block:
        - name: Clickhouse.download packages
          become: true
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: ./{{ item }}_{{ clickhouse_version }}_amd64.deb
            mode: 0644
          with_items: "{{ clickhouse_amd64_packages }}"
        - name: Clickhouse. Install clickhouse-common-static
          become: true
          apt:
            deb: ./clickhouse-common-static_{{ clickhouse_version }}_amd64.deb
          notify: Start clickhouse service
        - name: Clickhouse. Install clickhouse-client
          become: true
          apt:
            deb: "./clickhouse-client_{{ clickhouse_version }}_amd64.deb"
          notify: Start clickhouse service
        - name: Clickhouse. Install clickhouse-server
          become: true
          apt:
            deb: ./clickhouse-server_{{ clickhouse_version }}_amd64.deb
          notify: Start clickhouse service
        - name: Clickhouse. Flush handlers
          meta: flush_handlers
        - name: Clickhouse. Waiting while clickhouse-server is available...
          pause:
            seconds: 20
        - name: Create database
          command: "clickhouse-client -q 'create database log;'"
          register: create_db
          failed_when: create_db.rc != 0 and create_db.rc != 84
          changed_when: create_db.rc == 0
          retries: 10
          delay: 3
          until: create_db.rc == 0 or create_db.rc == 84
      tags: clickhouse
- name: Install Vector
  hosts: clickhouse
  handlers:
    - name: Restart vector service
      systemd:
        name: vector
        state: restarted
        enabled: true
      become: true
  tasks:
    - block:
        - name: Install vector packages
          become: true
          apt:
            deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
          notify: Restart vector service
        - name: Template a config vector
          become: true
          become_user: root
          template:
            src: templates/vector.toml
            dest: /etc/vector/vector.toml
            owner: root
            group: root
            mode: "0644"
          notify:
            - Restart vector service
      tags: vector