---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.117.180
      ansible_connection: ssh
      ansible_user: felimonist
      ansible_ssh_private_key_file: ~/.ssh/2
      ansible_python_interpreter: python3
    
